# general settings
name: MSA-ESRGAN-gvWgpS_x4_ip14v33-d2-cc128-wfix-v2
model_type: RealESRGANModel
scale: 4
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

# ----------------- options for synthesizing training data in RealESRGANModel ----------------- #
# USM the ground-truth
l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False

# the first degradation process
resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
resize_range: [0.15, 1.5]
gaussian_noise_prob: 0.5
noise_range: [1, 30]
poisson_scale_range: [0.05, 3]
gray_noise_prob: 0.4
jpeg_range: [15, 75]    # Lower both values from [30, 95] for more compression artifacts

# the second degradation process
second_blur_prob: 0.9    # Increase from 0.8 to 0.9
resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
resize_range2: [0.3, 1.2]
gaussian_noise_prob2: 0.5
noise_range2: [1, 25]
poisson_scale_range2: [0.05, 2.5]
gray_noise_prob2: 0.4
jpeg_range2: [15, 75]    # Lower both values from [30, 95]

gt_size: 256
queue_size: 180

batch_size_per_gpu: 5  # Changed from 4

datasets:
  train:
    name: iphone14+4kv33
    type: RealESRGANDataset
    dataroot_gt: datasets/ds_root
    # meta_info: datasets/ds_root/meta_info/meta_info_iphone14+4kv2_multiscale.txt
    meta_info: datasets/ds_root/meta_info/meta_info_ip14v33.txt

    io_backend:
      type: disk

    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 4.5]  # Increase upper bound from 3 to 4.5 for more blur
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 2.5]  # Increase upper bound from 1.5 to 2.5
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 0.8

    gt_size: 256  # Changed from 320
    use_hflip: True
    use_rot: False

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 5
    batch_size_per_gpu: 5  # Changed from 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # Uncomment these for validation
  val:
    name: validation
    type: PairedImageDataset
    dataroot_gt: datasets/ds_root/validation/hq2
    dataroot_lq: datasets/ds_root/validation/lq2_786k
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

network_d:
  type: UNetDiscriminator
  num_in_ch: 3
  num_feat: 128  # Keep at 128 for discriminator balance
  skip_connection: True

# path
path:
  # When using "auto_resume", for iteration zero the pretrain_network_g is used, otherwise
  # this BasicSR framework will just use the hightest iteration cound net_g, net_d, and state files

  # pretrain_network_g: experiments/pretrained_models/ESRnet_ip14v3_g_2950000.pth  # Real-ESRNet ip14+4kv3 using jpg dmg [15, 95]
  pretrain_network_g: experiments/pretrained_models/ESRnet_ip14v33_320gt_dmgV2_2995K.pth
  param_key_g: params_ema
  strict_load_g: true

  # pretrain_network_d: ~

  param_key_d: params_ema
  strict_load_d: true

  resume_state: experiments/MSA-ESRGAN-gvWgpS_x4_ip14v33-d2-cc128-wfix-v2/training_states/454680.state
  # experiments/MSA-ESRGAN-gvWgpS_x4_ip14v33-d2-cc128-wfix-v2/training_states/357850.state.updated
  # experiments/MSA-ESRGAN-gvWgpS_x4_ip14v33-d2-cc128-wfix-v2/training_states/223130.state.updated

  # Auto resume from cli just uses last net_g, net_d, and state files. Learning rates
  # are sealed into the state file as are all optimizer schedules.
  # as a result auto_resume will ignore yaml reconfigs on lr and milestones.

  # To keep training progress use the specific net_g, net_d without a state file
  # and mak70k, @119e modifications to lr and/or milestones as needed. Iteration count
  # will be reset to 0 and the optimizers will be reinitialized with new lr and
  # milestones if changed. Name the yaml as a series to help organize
  # tensorboard visuals since the charts are really just off-set continuations
  # of the original training run using a series of yml configs.
  # This is the same process for finetuning with pretrained networks but
  # different because the dataset hasn't changed.
  # Note: the --auto_resume flat is not used (unless a run is being interrupted
  # to check-in on progress using a test set).  Resuming from a specific point
  # would also not need the --auto_resume flag (since you specify the net_g,
  # and state file). Once a state file is specified, net_d will be inferred so
  # no need to specify net_d.  The cli --auto_resume flag just ignores the
  # pretrain_network_g parameter and uses the latest net_g and state file.


# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1.2505e-4
    weight_decay: 0
    betas: [0.5, 0.99]
  optim_d:
    type: Adam
    lr: !!float 2.501e-5  # Reduce from 5.002e-5 (LR too high)
    weight_decay: 0
    betas: [0.5, 0.99]   # beta1=0 disables Adam momentum
    # eps: 1e-8
  scheduler:
    type: MultiStepLR
    # Changes to lr and milestones do not natively work with resume since the
    # optimizer initial lr sched calc is held in mem and re-saved at each state.
    # Use the update_states.py script to modify state files to update LR
    # between restarts.
    # PyTorch milestons are epochs, BasicSR are iterations.
    milestones: [223131, 311541, 345221, 357851, 395741, 433631, 471521, 509411, 547301, 585191, 623081]
    gamma: 0.5

  # A dry-run will compute iterations per epoch.
  # Example, ip14+4kv3.2 dataset is 3802 iterations per epoch
  # Example, ip14v33 dataset is 4210 iterations per epoch
  total_iter: 842000  # 200 epochs for ip14v33 dataset
  warmup_iter: 4210

  net_d_iters: 10  # Run at 10 or higher for critic to compete
  # @5 the generator beats it so often it's almost like it gives-up,
  # d_gap shows convergence but falls below 5e-4 by iter 9k
  # gradients become very small by iter 20k needing big scale-up multiples.
  # It seems like scaling up even higher wgan weights that early (500, 300, 600)
  # in training probably confuses the training?
  # But then again, that run did not have a long net_d_init_iters period.
  # Using 2 full epochs (1 epoch with LR warmup) and 1 at full LR helped.
  #
  # @10 d_gap stays above 5e-4 until ~80k iters has has a more smooth fall-off
  # and the remaining decay looks smooth and healthy through 200k iters without
  # changing wgan weights.  d_gap starts to cross into small positive values
  # by 230k but does get pushed back to -3.xe-2 frequently.

  net_d_init_iters: 8420  # 2 full epochs, 1 with warmup and 2nd at full LR

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.00
    reduction: mean
  grad_opt:
    type: GradientVarianceLoss
    loss_weight: 0.200 # from 0.01, to 0.1 @223k (.018 inbetween), to 0.3 @416k, 0.4 @442k
    # drop to 0.2 @416k (model is searching too hard at 0.3)
    reduction: mean
  # perceptual loss (content and stylecompressor losses)
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv1_2': 0.1
      'conv2_2': 0.1
      'conv3_4': 1
      'conv4_4': 1
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 0.0065 # .005 to .0065 @277k
    style_weight: 0
    range_norm: false
    criterion: l1
  # gan loss
  gan_opt:
    type: RelativisticAverageGANLoss
    loss_type: wgan-gp
    gp_lambda: 10.0 # incr from 10 to 12 @iter 214k, 15.0 @223k
    loss_weight: !!float 430.0

# Uncomment these for validation
# validation settings
val:
  val_freq: 4210
  save_img: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: 4210
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
